import {
  Customer,
  Employee,
  MenuCafe,
  BilliardTable,
  Order,
  Payment,
  Reservation,
  RentalTransaction,
} from "@/types";

export const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "John Doe",
    email: "john.doe@email.com",
    phone: "+1234567890",
    address: "123 Main St, City",
    membershipType: "VIP",
    joinDate: "2023-01-15",
    totalSpent: 1250,
    loyaltyPoints: 125,
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@email.com",
    phone: "+1234567891",
    address: "456 Oak Ave, City",
    membershipType: "Regular",
    joinDate: "2023-03-20",
    totalSpent: 680,
    loyaltyPoints: 68,
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike.johnson@email.com",
    phone: "+1234567892",
    address: "789 Pine Rd, City",
    membershipType: "Premium",
    joinDate: "2022-12-10",
    totalSpent: 2100,
    loyaltyPoints: 210,
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "1",
    name: "Alice Brown",
    email: "alice.brown@company.com",
    phone: "+1234567893",
    position: "Manager",
    department: "Management",
    salary: 4500,
    hireDate: "2022-06-01",
    status: "Active",
    shift: "Morning",
  },
  {
    id: "2",
    name: "Bob Wilson",
    email: "bob.wilson@company.com",
    phone: "+1234567894",
    position: "Barista",
    department: "Cafe",
    salary: 2200,
    hireDate: "2023-02-15",
    status: "Active",
    shift: "Afternoon",
  },
  {
    id: "3",
    name: "Carol Davis",
    email: "carol.davis@company.com",
    phone: "+1234567895",
    position: "Billiard Attendant",
    department: "Billiard",
    salary: 2000,
    hireDate: "2023-04-01",
    status: "Active",
    shift: "Night",
  },
];

export const mockMenuCafe: MenuCafe[] = [
  {
    id: "1",
    name: "Espresso",
    category: "Beverage",
    price: 3.5,
    description: "Rich and bold espresso shot",
    ingredients: ["Espresso beans", "Water"],
    availability: true,
    preparationTime: 2,
    imageUrl: "/placeholder.svg",
  },
  {
    id: "2",
    name: "Cappuccino",
    category: "Beverage",
    price: 4.5,
    description: "Espresso with steamed milk and foam",
    ingredients: ["Espresso beans", "Milk", "Milk foam"],
    availability: true,
    preparationTime: 5,
    imageUrl: "/placeholder.svg",
  },
  {
    id: "3",
    name: "Club Sandwich",
    category: "Food",
    price: 8.5,
    description: "Triple-layer sandwich with chicken, bacon, and vegetables",
    ingredients: ["Bread", "Chicken", "Bacon", "Lettuce", "Tomato", "Mayo"],
    availability: true,
    preparationTime: 10,
    imageUrl: "/placeholder.svg",
  },
  {
    id: "4",
    name: "Chocolate Cake",
    category: "Dessert",
    price: 5.5,
    description: "Rich chocolate cake with ganache",
    ingredients: ["Chocolate", "Flour", "Sugar", "Eggs", "Butter"],
    availability: true,
    preparationTime: 3,
    imageUrl: "/placeholder.svg",
  },
];

export const mockBilliardTables: BilliardTable[] = [
  {
    id: "1",
    tableNumber: 1,
    type: "8-Ball",
    status: "Available",
    hourlyRate: 12,
    location: "Main Floor - Section A",
    condition: "Excellent",
  },
  {
    id: "2",
    tableNumber: 2,
    type: "9-Ball",
    status: "Occupied",
    hourlyRate: 15,
    location: "Main Floor - Section A",
    condition: "Good",
  },
  {
    id: "3",
    tableNumber: 3,
    type: "Snooker",
    status: "Reserved",
    hourlyRate: 20,
    location: "VIP Section",
    condition: "Excellent",
  },
  {
    id: "4",
    tableNumber: 4,
    type: "8-Ball",
    status: "Maintenance",
    hourlyRate: 12,
    location: "Main Floor - Section B",
    condition: "Needs Repair",
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    customerId: "1",
    customerName: "John Doe",
    items: [
      {
        menuId: "1",
        menuName: "Espresso",
        quantity: 2,
        unitPrice: 3.5,
        subtotal: 7.0,
      },
      {
        menuId: "3",
        menuName: "Club Sandwich",
        quantity: 1,
        unitPrice: 8.5,
        subtotal: 8.5,
      },
    ],
    totalAmount: 16.95,
    orderDate: "2024-01-20T10:30:00Z",
    status: "Served",
    tableNumber: 5,
    notes: "Extra hot espresso",
    discount: 0,
    tax: 1.45,
  },
  {
    id: "2",
    customerId: "2",
    customerName: "Jane Smith",
    items: [
      {
        menuId: "2",
        menuName: "Cappuccino",
        quantity: 1,
        unitPrice: 4.5,
        subtotal: 4.5,
      },
      {
        menuId: "4",
        menuName: "Chocolate Cake",
        quantity: 1,
        unitPrice: 5.5,
        subtotal: 5.5,
      },
    ],
    totalAmount: 10.9,
    orderDate: "2024-01-20T14:15:00Z",
    status: "Preparing",
    tableNumber: 3,
    discount: 0,
    tax: 0.9,
  },
];

export const mockPayments: Payment[] = [
  {
    id: "1",
    orderId: "1",
    amount: 16.95,
    paymentMethod: "Credit Card",
    paymentDate: "2024-01-20T10:35:00Z",
    status: "Completed",
    transactionId: "TXN123456789",
    cashierName: "Alice Brown",
  },
  {
    id: "2",
    orderId: "2",
    amount: 10.9,
    paymentMethod: "Cash",
    paymentDate: "2024-01-20T14:20:00Z",
    status: "Completed",
    cashierName: "Bob Wilson",
    change: 4.1,
  },
];

export const mockReservations: Reservation[] = [
  {
    id: "1",
    customerId: "1",
    customerName: "John Doe",
    customerPhone: "+1234567890",
    tableId: "3",
    tableNumber: 3,
    reservationDate: "2024-01-21",
    startTime: "19:00",
    endTime: "21:00",
    duration: 2,
    status: "Confirmed",
    partySize: 4,
    specialRequests: "VIP service",
    deposit: 40,
  },
  {
    id: "2",
    customerId: "3",
    customerName: "Mike Johnson",
    customerPhone: "+1234567892",
    tableId: "1",
    tableNumber: 1,
    reservationDate: "2024-01-22",
    startTime: "18:30",
    endTime: "20:30",
    duration: 2,
    status: "Pending",
    partySize: 2,
    deposit: 24,
  },
];

export const mockRentalTransactions: RentalTransaction[] = [
  {
    id: "1",
    customerId: "2",
    customerName: "Jane Smith",
    tableId: "2",
    tableNumber: 2,
    startTime: "2024-01-20T15:00:00Z",
    duration: 1.5,
    hourlyRate: 15,
    totalAmount: 22.5,
    status: "Active",
    additionalServices: ["Cue rental", "Chalk"],
    employeeId: "3",
    employeeName: "Carol Davis",
    paymentStatus: "Unpaid",
  },
  {
    id: "2",
    customerId: "1",
    customerName: "John Doe",
    tableId: "1",
    tableNumber: 1,
    startTime: "2024-01-19T20:00:00Z",
    endTime: "2024-01-19T22:00:00Z",
    duration: 2,
    hourlyRate: 12,
    totalAmount: 24,
    status: "Completed",
    additionalServices: [],
    employeeId: "3",
    employeeName: "Carol Davis",
    paymentStatus: "Paid",
  },
];
